version: '3.8'
services:
  mongodb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    # ports:
    #   - "27017:27017"
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=$MONGODB_USER
      - MONGODB_INITDB_ROOT_PASSWORD=$MONGODB_PASS
    volumes:
      - $PWD/data/db:/data/db


  bigkinds-loader:
    build:
      context: .
      args:
        UID: $UID
        GID: $GID
        USER: $DOCKER_USER
        PROJ: $PROJ
    image: 0jacky/$PROJ:latest
    container_name: bigkinds-loader
    depends_on:
      - mongodb
    environment:
      - CONN_STR=mongodb://$MONGODB_USER:$MONGODB_PASS@mongodb
      - PLAYWRIGHT_BROWSERS_PATH=/home/$DOCKER_USER/.cache/ms-playwright
    volumes:
      - $PWD/config:/home/$DOCKER_USER/$PROJ/config
      - $PWD/log:/home/$DOCKER_USER/$PROJ/log
      - $PWD/data:/home/$DOCKER_USER/$PROJ/data
      - $PWD/bigkinds_loader:/home/$DOCKER_USER/$PROJ/bigkinds_loader
      - $PWD/scripts:/home/$DOCKER_USER/$PROJ/scripts
    command: python scripts/run.py


  pytest:
    image: 0jacky/$PROJ:latest
    container_name: pytest
    # environment:
    volumes:
      - $PWD/config:/home/$DOCKER_USER/$PROJ/config
      - $PWD/log:/home/$DOCKER_USER/$PROJ/log
      - $PWD/data:/home/$DOCKER_USER/$PROJ/data
      - $PWD/src:/home/$DOCKER_USER/$PROJ/src
      - $PWD/tests:/home/$DOCKER_USER/$PROJ/tests
    command: pytest


  doc:
    image: 0jacky/$PROJ:latest
    container_name: doc
    volumes:
        - $PWD/src:/home/$DOCKER_USER/$PROJ/src
        - $PWD/docs:/home/$DOCKER_USER/$PROJ/docs
    command: bash -c "rm -f docs/bigkinds_loader* && sphinx-apidoc -o docs bigkinds_loader && cd docs && make clean html"


  # shell command: docker compose run --rm --service-ports jupyter
  jupyter-lab:
    image: 0jacky/$PROJ:latest
    container_name: jupyter-lab
    depends_on:
      - mongodb
    environment:
      - CONN_STR=mongodb://$MONGODB_USER:$MONGODB_PASS@mongodb
    ports:
      - "8888:8888"
    volumes:
      - $PWD/config:/home/$DOCKER_USER/$PROJ/config
      - $PWD/log:/home/$DOCKER_USER/$PROJ/log
      - $PWD/data:/home/$DOCKER_USER/$PROJ/data
      - $PWD/bigkinds_loader/:/home/$DOCKER_USER/$PROJ/bigkinds_loader
      - $PWD/examples:/home/$DOCKER_USER/$PROJ/examples
      - $PWD/scripts:/home/$DOCKER_USER/$PROJ/scripts
    command: jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root
