hydra:
  output_subdir: null
  run:
    dir: .


defaults:
  - _self_


# 경향신문
# 한겨레
# 한국일보
# 매일경제
press: 한국경제
timeout: 300000
begin: 2024-01-01
end: 2024-01-01
db_name: 한국경제
collection_name: 2024-01-01
